data:
  test_size: 0.2
  random_state: 42

experiments:
  split_validation:
    ratios: [30, 20, 10] # Merepresentasikan test_size 30%, 20%, 10%
  k_fold_validation:
    folds: [5, 10]
    k_values_for_knn: [5, 10]